blank_issues_enabled: true
contact_links:
  - name: ğŸ“š Documentation
    url: https://github.com/dennisdoomen/reflectify
    about: Read our comprehensive documentation.
  - name: â­ Sponsor Reflectify
    url: https://github.com/sponsors/dennisdoomen
    about: Help the continued development.
  - name: ğŸ’¬ Ask on Stack Overflow
    url: https://stackoverflow.com/questions/tagged/reflectify
    about: The best place for asking general purpose questions.